FROM python:3.10

# 작업 디렉토리 설정
WORKDIR /app

# 프로젝트 코드 복사
COPY . .

# 의존성 설치
RUN pip install --no-cache-dir -r requirements.txt

# .env 파일 로딩용
RUN pip install python-dotenv

# FastAPI 실행
CMD ["uvicorn", "main_2:app", "--host", "0.0.0.0", "--port", "8000"]

