# Flutter 정적 웹 파일을 서비스할 NGINX 베이스 이미지
FROM nginx:stable-alpine

# Flutter build 결과 복사
COPY build/web /usr/share/nginx/html

# (선택) SPA 라우팅 처리용 NGINX 설정 복사
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

